name: Deploy CentOS 9 on GCP and Configure via Ansible

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted 

    env:
      TF_VAR_project_id: "testjune13-462806"
      TF_VAR_credentials_file: "/home/shruti/sec.json"
      TF_VAR_public_key_path: "/home/shruti/.ssh/id_rsa.pub"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          chmod 600 /home/shruti/.ssh/id_rsa
          chmod 644 /home/shruti/.ssh/id_rsa.pub

      - name: Install Terraform and Ansible on CentOS 9
        run: |
          # Enable required repos
          sudo dnf install -y dnf-plugins-core epel-release
      
          # Install Ansible from EPEL
          sudo dnf install -y ansible
      
          # Add HashiCorp repo and install Terraform
          sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          sudo dnf -y install terraform
      
          # Confirm versions
          terraform -version
          ansible --version

      - name: Terraform Init
        run: |
          cd terraform-ansible
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform-ansible
          terraform apply -auto-approve

      - name: Get Terraform output (IP)
        id: get_ip
        run: |
          cd terraform-ansible
          terraform output -raw instance_ip > ip.txt

      - name: Prepare Ansible inventory
        run: |
          cd terraform-ansible 
          echo "[centos9]" > inventory
          echo "$(cat ip.txt) ansible_user=centos ansible_ssh_private_key_file=/home/shruti/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3" >> inventory

      - name: Run Ansible Playbook
        run: |
          cd terraform-ansible
          ansible-playbook -i inventory playbook.yaml
